config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
      devise_scope :admin do
		get "admins/users/list",
		to: "admins/sessions#list",
		as: "users_list"
	end
    
  resources :zombies do
    resources :brains
  end
  
  	
  
    root to: 'zombies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "ZombiesApplication" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="top-bar foundation-5-top-bar">
    <div class="top-bar-title">
      <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
        <button class="menu-icon" type="button" data-toggle></button>
      </span>
      <strong> LUISMAEL </strong> 
    </div>
    <div id= "responsive-menu">
      <div class="top-bar-left">
        <ul class="dropdown vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown" data-auto-height="true" data-animate-height="true">
          <li><a href="#">Menu Zombies</a>
            <ul class="menu">
              <li><%= link_to 'Lista Zombie', zombies_path %> </li>
              <li><%= link_to 'Nuevo Zombie', new_zombie_path %> </li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="top-bar-right">
      
        <% if user_signed_in? %>
          <strong> Bienvenido(a) <%= current_user.email %></strong><br>
          <strong> <%= link_to "cerrar sesion", destroy_user_session_path, method: :delete %></strong>
          <strong> <%= link_to "editar", edit_user_registration_path %></strong>
        <% elsif admin_signed_in? %>
          <strong> Bienvenido(a) <%= current_admin.email %></strong><br>
          <strong> <%= link_to "cerrar sesion", destroy_admin_session_path, method: :delete %></strong>
          <strong> <%= link_to "editar", edit_admin_registration_path %></strong>
        <% else %>
          <strong> <%= link_to "Login", new_user_session_path %></strong><tab>
          <strong> <%= link_to "Registro", new_user_registration_path %></strong>
        <%end%>
      </div>
    </div>
  </div>
  <% if notice %>
    <p class="alert alert-success"><%=notice%></p>
  <%end%>
  <% if alert %>
    <p class="alert alert-danger"><%=alert%></p>
  <%end%>
    <%= yield %>

  </body>
</html>